### ISSUE TITLE
ng-file-select: no input element on custom element

### ISSUE THREAD

**Issue by Frank3K** [danialfarid/angular-file-upload#460]
I'm using the wonderful [Angular Material project](https://github.com/angular/material/) for the styling of a webpage. It lets you use directives and services to apply the [Material Design principles](https://www.google.com/design/spec/material-design/) on a web page. One of these directives is the `md-button`, which can be used to create a button element that is styled conform these principles.

I have tried to use `md-button` in combination with the `ng-file-select` attribute. However, it seems that these two don't mix. When I use a regular `button` element, everything seems to work fine. See the following [plnkr](http://plnkr.co/edit/MzNYVbggjCLVM2xxZ5SS?p=preview).

As you can see in the demo the `button` element has an `input` child and the `md-button` has not. In the [angular-file-upload code](https://github.com/danialfarid/angular-file-upload/blob/5c5d7189b0722f0f4e5096cabba680b93205fc82/dist/angular-file-upload.js#L196) I can see the `input` element being added. Unfortunately, in the end it is not there as child of the `md-button`. 

I think the `md-button` directive might have replaced or removed the `input` element, but I am not sure. Maybe it has something to do with the order in which both directives are executing?

As a solution I tried to change the `.append(fileElem)` in `.after(fileElem)` and that works. Appending the `fileElem` to the document body also works, but then one would need to destroy the corresponding `input` when removing the element.

**Comment by danialfarid** [comment]
For now you can just use `<input type="file"...>` instead of `button`.

**Comment by danialfarid** [comment]
@Frank3K I changed the way the input file is being added to the dom so it should fixes those issues since version 2.2.2.

@fcbenoit that was a separate issue which is fixed in the latest.

@timsmiths 
the first 3 should work now, ng-if still doesn't work since angular will not reattach event listener and will just clone the elements. So the change event listeners on the file input will be removed. I believe ng-if would break any directive that binds events to the dom elements.

**Comment by Frank3K** [comment]
Can confirm this is working. Thanks!

**Comment by brianfeister** [comment]
As of version `4.2.1` of this directive and Angular Material version `0.10.1`, I had this working without issue, when I updated to ng-file-upload version `9.0.13` it is broken (no change the the `angular-material` version, just this directive).  I'm trying to figure out why it's broken.  It's interesting that the `<md-menu>` directive appends it's menu to the DOM, I would expect this to break functionality for a directive like this (which is appending a separate file `<input>` element to the DOM).  But for some reason, it works in version `4.2.1` and is broken in `9.0.13`.  Any thoughts about this @danialfarid ?

**Comment by danialfarid** [comment]
What is broken? any errors?

**Comment by danialfarid** [comment]
Make sure to read the release notes, there have been non backwards compatible changes since version 4.

**Comment by brianfeister** [comment]
Thanks @danialfarid for getting back to me, I did study the release notes carefully and I think I've updated everything properly.  There are no errors, but it appears a watcher on the `ng-model` fires at the time the button is clicked rather than waiting until after I select a file from the browser's file selection modal.  Previously the `ngModel` would not fire a change event until after selection was complete.  

Ugh.  Unfortunately in the process of creating an example of the problem, I proved that it's something else I've not accounted for.  This example shows that it does work (disproving my earlier comment).  I will add a further update if I can track down the problem with my implementation of it.

Thanks for being so quick to respond, here's the working demo:

http://codepen.io/brianfeister/pen/MarYdQ

**Comment by brianfeister** [comment]
Actually, @danialfarid forget what I said before, the demo does in fact show the error. File upload from within the dropdown works, while the one outside of it does not... I managed to reproduce it after all :)

http://codepen.io/brianfeister/pen/MarYdQ

**Comment by brianfeister** [comment]
Here is an example of the same code working correctly with version `4.2.1` http://codepen.io/brianfeister/pen/mepJKW

**Comment by danialfarid** [comment]
@brianfeister  Fixed at version 9.0.15

**Comment by brianfeister** [comment]
Awesome! Thanks @danialfarid

**Comment by andreipot** [comment]
@danialfarid  is this working with angular 1.5.5? I'm using ng-file-upload v12.0.4 but when i select files, files are not bound to ng-model.

**Comment by danialfarid** [comment]
@andreipot yes try it on the demo page. You can change the angular version on top right corner.
