### ISSUE TITLE
Adding costume attributes to <input type="file">

### ISSUE THREAD

**Issue by hafezdivandari** [danialfarid/angular-file-upload#462]
Is it possible to add a costume property like `webkitdirectory` into input element?

     <button ng-file-select ng-model="myFolder" ng-multiple="true" webkitdirectory>Upload folder</button>

**Comment by danialfarid** [comment]
Not at the moment, User input type="file" instead.

**Comment by danialfarid** [comment]
I think it makes sense to use `<input type="file"...` for these cases since those attributes are for that specific element. 
The problem is that if you don't use input type file an invisible input type file will be created inside that element and there is no way to tell which directive/attribute is for which element. For example there might be a directive or attribute which is only for `button` and you don't want it to be on the `input` so I cannot just copy all attributes to `input` element.

**Comment by danialfarid** [comment]
fixed in version 2.2.1.
You can prefix the attribute with '(data-)input-file-` and it would propagate it to the underlying input type file. In this case `<button ng-file-select ng-model="myFolder" ng-multiple="true" input-file-webkitdirectory>Upload folder</button>`
