### ISSUE TITLE
Doesn't work "resetOnClick"

### ISSUE THREAD

**Issue by grvldmr** [danialfarid/angular-file-upload#499]
i try this

```
<button ng-file-select ng-model="myFiles" ng-multiple="true" resetOnClick="false">Upload</button>
```

but file list reset after new file\files selected.

**Comment by danialfarid** [comment]
This will be removed in the next release and will be always true since Chrome by default resets the input after you select or cancel the file select popup.

**Comment by danialfarid** [comment]
So `resetOnClick="false"` only works for some browsers at the moment.

**Comment by danialfarid** [comment]
This option is removed since 3.0,0. 
It would always consider it as true since Chrome browser fires file change when you cancel the popup. So this will make the other browsers to act the same way allowing the user to cancel the selected file by clicking cancel on the popup, and also allowing them to upload the same file again.
