### ISSUE TITLE
Missing referer header in flash fallback

### ISSUE THREAD

**Issue by defrex** [danialfarid/angular-file-upload#516]
The flash fallback doesn't send the HTTP Referer header.

The reason I need it, if your curious, is due to [Django's CSRF protection](https://docs.djangoproject.com/en/dev/ref/csrf/#how-it-works). When requesting via SSL, it confirms that the referer matches the sites domain. Without the referer header, every request will 403.

**Comment by danialfarid** [comment]
Custom headers are not supported for flash fallback. It is mentioned in the docs.

**Comment by defrex** [comment]
Ya, I saw that. Referer isn't really a custom header though, given that every other request the browser makes includes it. Is it not possible to implement? If not, I'll have to peruse a workaround of some kind.

BTW, I was looking through the code for the flash source and had trouble finding it. Mind pointing me in the right direction?

**Comment by danialfarid** [comment]
Yea you should find a workaround for it, probably sending it as a request parameter and have the server to consider it as header.

The flash code is in `angular-file-upload-shim.js`. It loads the [FileAPI](https://github.com/mailru/FileAPI) on demand if FormData is not defined in the browser. The FileAPI js an flash files are also included in ths plugin since it only works with specific version of it and there's been  small  changes to it too.
