### ISSUE TITLE
Sample code: $watch firing upon page load

### ISSUE THREAD

**Issue by clabough** [danialfarid/angular-file-upload#525]
Using the sample code, the upload event is firing twice upon loading of the page.  I had to change it to this to prevent that.

		$scope.$watch('files', function() {
		if ($scope.files == null) return;  //<- Added this line
		$scope.upload = $upload.upload({
      url: 'server/upload/url',
      data: {myObj: $scope.myModelObj},
      file: $scope.files
    }).progress(function(evt) {
      console.log('progress: ' + parseInt(100.0 * evt.loaded / evt.total) + '% file :'+ evt.config.file.name);
    }).success(function(data, status, headers, config) {
      console.log('file ' + config.file.name + 'is uploaded successfully. Response: ' + data);
    });
		}

Also, evt.config.file.name and config.file.name are undefined.  Using the latest Chrome and .NET Web API backend. Note: I determined that using evt.config.file[0].name worked.

**Comment by Ilkorn** [comment]
Please comment this becouse it's truely important issue.

**Comment by danialfarid** [comment]
I updated the readme to have `evt.config.file[0].name` instead of `evt.config.file.name` which was wrong.

The change event is firing twice because when you click on the button it set's the value to null to handle the case when user cancels the popup (there is no easy way to detect this event in browsers other than Chrome which by default sets the value to null) and selecting the same file again.
So you are doing it right if the files are empty you don't need to upload anything but that is a correct event since the user might cancel the selected file and that's why you get that model change.

**Comment by danialfarid** [comment]
Actually the problem with `file[0]` was the way the file was passed in to the upload, it should've been `$scope.files[0]` I have updated the readme.

**Comment by jordancrawfordnz** [comment]
It says ````file.lenght```` in the sample JavaScript.

Also, I needed ````$scope.files = [];````

**Comment by danialfarid** [comment]
I have updated the sample and included a jsfiddle to show how it works in version 3.0.0
